### ISSUE TITLE
null pointer dereference in LinearRgb (butteraugli_comparator.cc:43)

### ISSUE THREAD

**Issue by geeknik** [google/guetzli#29]
Compiled with afl-clang-fast.

./guetzli --quality 78 [test000](https://github.com/google/guetzli/files/715056/test000.gz) /dev/null

```
ASAN:DEADLYSIGNAL
=================================================================
==21996==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000004fa40d bp 0x62300000e140 sp 0x7fffb7d6b530 T0)
    #0 0x4fa40c in LinearRgb /root/guetzli/guetzli/butteraugli_comparator.cc:43
    #1 0x4fa40c in guetzli::ButteraugliComparator::ButteraugliComparator(int, int, std::vector<unsigned char, std::allocator<unsigned char> > const&, float, guetzli::ProcessStats*) /root/guetzli/guetzli/butteraugli_comparator.cc:63
    #2 0x5e414d in guetzli::Process(guetzli::Params const&, guetzli::ProcessStats*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) /root/guetzli/guetzli/processor.cc:854
    #3 0x41a99c in main /root/guetzli/guetzli/guetzli.cc:228
    #4 0x7fbef01432b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #5 0x41b819 in _start (/root/guetzli/bin/Debug/guetzli+0x41b819)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /root/guetzli/guetzli/butteraugli_comparator.cc:43 in LinearRgb
==21996==ABORTING
```

**Comment by jyrkialakuijala** [comment]
We are looking at this.
