### ISSUE TITLE
Null pointer dereference in ProcessJpegData (processor.cc:790)

### ISSUE THREAD

**Issue by josephbisch** [google/guetzli#38]
Compiled with afl-g++ and ASan.

./guetzli [id:000000,sig:06,src:000000,op:flip2,pos:164.min](https://github.com/google/guetzli/files/849042/id.000000.sig.06.src.000000.op.flip2.pos.164.min.zip) /dev/null

(linked file is a zip file...unzip first before running above command)

```
ASAN:DEADLYSIGNAL
=================================================================
==25977==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x55a45ae98e29 bp 0x7ffd18ad4a90 sp 0x7ffd18ad4540 T0)
    #0 0x55a45ae98e28 in ProcessJpegData guetzli/processor.cc:790
    #1 0x55a45aeaecda in guetzli::ProcessJpegData(guetzli::Params const&, guetzli::JPEGData const&, guetzli::Comparator*, guetzli::GuetzliOutput*, guetzli::ProcessStats*) guetzli/processor.cc:836
    #2 0x55a45aeaecda in guetzli::Process(guetzli::Params const&, guetzli::ProcessStats*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) guetzli/processor.cc:863
    #3 0x55a45adb2dcf in main guetzli/guetzli.cc:237
    #4 0x7fe6dc95d2b0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x202b0)
    #5 0x55a45adb3b69 in _start (/home/joseph/fuzz/guetzli/guetzli-afl-debug/bin/Debug/guetzli+0xab69)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV guetzli/processor.cc:790 in ProcessJpegData
==25977==ABORTING
```

**Comment by josephbisch** [comment]
This is on commit 9faf961e1bd9a72d6d17f813a33dfaecdfee1965 btw.

**Comment by robryk** [comment]
Thank you for the report. It appears that I've ended up introducing this when I fixed another problem with small images.
